stages:
  - test
  - build
  - deploy
unit-test:
  stage: test
  script: "/home/dlozan/Unity/Hub/Editor/2019.3.4f1/Editor/Unity.app/Contents/Linux/Unity \
              -batchmode \
              -projectPath . \
              -runTests -testPlatform editmode \
              -logFile \
              -testResults ./unit-tests.xml"
  tags:
    - unity
unity-build:
  stage: build
  script: echo 'Building...'
  tags:
    - unity
playstore:
  stage: deploy
  script: echo 'Deploying...'
  tags:
    - unity